### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by cvonder1** [leonm13/Collaborative_Filtering#3]
Some way of tracking dependencies for easy installation with pip.

**Comment by cvonder1** [comment]
As far as I see it, we have the following dependencies:
- numpy
- pytest
- pytest-mock

**Comment by dkettner** [comment]
As of now also:
timeit (in create_all_simillarites)
warning (to ignore the RuntimeWarning)

**Comment by cvonder1** [comment]
OK, but both are part of the standard python modules, so they do not need to be installed additionally.
